name: "Build"

on:
  workflow_call:
    inputs:
      build-command:
        required: true
        type: string
    secrets:
      GPG_KEY:
        required: true
      MAVEN_USER_TOKEN:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_USER_TOKEN: ${{ secrets.MAVEN_USER_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - name: Import GPG key
        run: echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_KEY }}
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew clean ${{ inputs.build-command }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/*
      - name: Create bundle.zip
        if: inputs.build-command == 'publishMavenPublicationToLocalRepository'
        run: |
            cd build/repos/local
            zip -r ../../../bundle.zip .
            cd ../../..
      - name: Upload to Maven Central Portal
        if: inputs.build-command == 'publishMavenPublicationToLocalRepository'
        run: |
            curl --request POST \
            --verbose \
            --header "Authorization: Bearer $MAVEN_USER_TOKEN" \
            --form bundle=@bundle.zip \
            https://central.sonatype.com/api/v1/publisher/upload?publishingType=USER_MANAGED
